force-app/main/default/objects/Message__c/Message__c.object-meta.xml
<CustomObject>
    <description>Slack, but better ;)</description>
    <label>Message</label>
    <nameField>
        <label>Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Message__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Messages</relationshipLabel>
    <relationshipName>Messages</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/MessageController.cls
public with sharing class MessageController {

    public class MessageException extends Exception {
        // No implementation
    }
    /*
	* LWC @wire requires Cacheable=true flag
	**/
	@AuraEnabled(Cacheable=true)
    public static List<Message__c> getAllMessages() {
        List<Message__c> messages = [ SELECT Id, Name, Account__r.Name, Account__c, CreatedDate FROM Message__c ORDER BY CreatedDate ];
        return messages;
    }
    
	@AuraEnabled(Cacheable=true)
    public static List<Message__c> getMyMessages(String accountId) {
        // return List<Message__c> messages = [ SELECT Id, Name FROM Message__c WHERE Account__c =: accountId];
        List<Message__c> messages = [ SELECT Id, Name, Account__r.Name, Account__c, CreatedDate FROM Message__c WHERE Account__c =: accountId ORDER BY CreatedDate  ];
        return messages;
    }
    
    /*
	* LWC imperatively call this, no need for Cacheable=true flag
	**/
	@AuraEnabled
    public static Message__c sendMessage(String msg, String accountId) {
        System.debug('About to create message on with AccountId: ' + accountId + '. Message: ' + msg);

        Message__c new_msg = new Message__c(
            Name = msg,
            Account__c = accountId
        );
        upsert new_msg;
        System.debug('Created message on with AccountId: ' + new_msg.Account__c + '. Message: ' + new_msg.Name);

        return new_msg;
    }
}